pipeline:
  build:
    image: golang:${TAG}
    commands:
      - apt-get update
      - apt-get install libmagic-dev
      - go get github.com/axw/gocov
      - go get github.com/mattn/goveralls
      - go get golang.org/x/tools/cmd/cover
      - go get
      - go build
      - go test

matrix:
  TAG:
    - 1.8
    - latest