workspace:
  base: /go
  path: src/github.com/depado/go-b0tsec

matrix:
  TAG:
    - 1.8
    - latest

pipeline:
  build:
    image: golang:${TAG}
    commands:
      - apt-get update
      - apt-get install -y libmagic-dev
      - go get github.com/axw/gocov
      - go get github.com/mattn/goveralls
      - go get golang.org/x/tools/cmd/cover
      - go get
      - go build
      - go test