sudo: false
language: go

go:
  - 1.5

go_import_path: github.com/depado/go-b0tsec

env:
  - GOARCH=amd64
  - GOARCH=arm

addons:
    apt:
        packages:
        - libmagic-dev

before_install:
  - go get github.com/axw/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
  - go get github.com/go-playground/overalls

script:
  - go test -i ./...
  - $GOPATH/bin/overalls -project=github.com/depado/go-b0tsec -debug
  - $GOPATH/bin/goveralls -coverprofile=overalls.coverprofile -service=travis-ci
